// GENERATED by etl/src/etl/pwa.py (_middleware_js). Do not edit here:
// the Content-Security-Policy carries hashes of the inline scripts in
// the generated pages, so it has to be produced alongside them. Edit
// pwa.py and rebuild.
//
// Why the headers are here rather than in _headers: Cloudflare applies
// _headers to static asset responses, but every HTML response is
// returned through this middleware and does not pick that file up. The
// image cache rule worked live while the header block on /index.html
// silently did not.
const CSP = {
  "/": "default-src 'self'; script-src 'self' 'sha256-GOVf2XLN6YqTqv+FjMEE9czvD0wlaEesAYmV9x6m0PQ=' 'sha256-E2QRd3PoMO+vnBBbf9slncCCXqmmYNMAWp2W8qwCLjI='; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://whereabouts-errors.adam-wc-sweepstake.workers.dev https://counterscale.adam-wc-sweepstake.workers.dev; manifest-src 'self'; worker-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'",
  "/index.html": "default-src 'self'; script-src 'self' 'sha256-GOVf2XLN6YqTqv+FjMEE9czvD0wlaEesAYmV9x6m0PQ=' 'sha256-E2QRd3PoMO+vnBBbf9slncCCXqmmYNMAWp2W8qwCLjI='; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://whereabouts-errors.adam-wc-sweepstake.workers.dev https://counterscale.adam-wc-sweepstake.workers.dev; manifest-src 'self'; worker-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'",
  "/how-it-works.html": "default-src 'self'; script-src 'self' ; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://whereabouts-errors.adam-wc-sweepstake.workers.dev https://counterscale.adam-wc-sweepstake.workers.dev; manifest-src 'self'; worker-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'",
  "/privacy.html": "default-src 'self'; script-src 'self' ; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; font-src 'self'; connect-src 'self' https://whereabouts-errors.adam-wc-sweepstake.workers.dev https://counterscale.adam-wc-sweepstake.workers.dev; manifest-src 'self'; worker-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'"
};

const COMMON = {
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "no-referrer",
  "X-Frame-Options": "DENY",
  "Permissions-Policy": "geolocation=(), camera=(), microphone=(), payment=(), usb=()",
};

export async function onRequest(context) {
  const url = new URL(context.request.url);
  if (url.hostname.endsWith('.pages.dev')) {
    url.protocol = 'https:';
    url.hostname = 'whereabouts.adamdent.uk';
    return Response.redirect(url.toString(), 301);
  }
  const response = await context.next();
  // Headers on the response from context.next() are immutable, so the
  // response has to be rebuilt to add to them.
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(COMMON)) headers.set(k, v);
  const csp = CSP[url.pathname];
  if (csp) headers.set('Content-Security-Policy', csp);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
