"""District coverage tracking (spec §8 Phase 4/8): what's discovered, parsed, and placed.

Regenerated on every ETL run and written to data/dist/coverage.md, which is
git-tracked, so "what's done and what's left" survives across sessions without
a separate database. Measured against the *full* DISTRICT_INDEXES registry, not
just whatever districts a given run touched, so districts not yet processed at
all still show up as "not started" rather than disappearing from the picture.
"""

from __future__ import annotations

import json
from pathlib import Path

from .discover import DISTRICT_INDEXES


def _load(path: Path) -> list[dict]:
    return json.loads(path.read_text()) if path.exists() else []


def build_coverage_report(dist_dir: Path, placements_dir: Path) -> str:
    sheets = _load(dist_dir / "sheets.json")
    houses = _load(dist_dir / "houses.json")

    sheet_district = {s["id"]: s["district"] for s in sheets}

    sheets_by_district: dict[str, int] = {}
    for s in sheets:
        sheets_by_district[s["district"]] = sheets_by_district.get(s["district"], 0) + 1

    houses_by_district: dict[str, int] = {}
    for h in houses:
        d = sheet_district.get(h["sheet_id"])
        if d:
            houses_by_district[d] = houses_by_district.get(d, 0) + 1

    placed_by_district: dict[str, int] = {}
    for s in sheets:
        placement_file = placements_dir / f"{s['id']}.json"
        if placement_file.exists():
            saved = json.loads(placement_file.read_text())
            n = len(saved.get("houses", {}))
            placed_by_district[s["district"]] = placed_by_district.get(s["district"], 0) + n

    lines = [
        "# Coverage report\n",
        "Regenerated by the ETL on every run — do not edit by hand. "
        "Districts are processed one at a time (`--district \"<name>\"`); "
        "see SPEC.md §8 Phase 4/8 for the workflow.\n",
        "| District | Status | Sheets | Houses | Placed |",
        "|---|---|---:|---:|---:|",
    ]

    total_sheets = total_houses = total_placed = 0
    for district in DISTRICT_INDEXES:
        n_sheets = sheets_by_district.get(district, 0)
        n_houses = houses_by_district.get(district, 0)
        n_placed = placed_by_district.get(district, 0)
        total_sheets += n_sheets
        total_houses += n_houses
        total_placed += n_placed

        if n_sheets == 0:
            status = "not started"
        elif n_houses > 0 and n_placed >= n_houses:
            status = "complete"
        elif n_placed > 0:
            status = "in progress"
        else:
            status = "parsed, not yet placed"

        placed_col = f"{n_placed}/{n_houses}" if n_houses else "–"
        lines.append(f"| {district} | {status} | {n_sheets} | {n_houses} | {placed_col} |")

    lines.append(f"| **Total** | | **{total_sheets}** | **{total_houses}** | **{total_placed}/{total_houses}** |")

    unregistered = sorted(set(sheet_district.values()) - set(DISTRICT_INDEXES))
    if unregistered:
        lines.append("\n## Sheets outside DISTRICT_INDEXES\n")
        lines.append(
            "These districts appear in the emitted data but not in `discover.py`'s "
            "`DISTRICT_INDEXES` — likely stale data from a renamed/removed district:\n"
        )
        for d in unregistered:
            lines.append(f"- {d}")

    return "\n".join(lines) + "\n"
